export const AddUserToStore = "USER.ADDUSERTOSTORE";
export const AddStuToStore = "STUDENT.ADDUSERTOSTORE";
export const ADD_PRODUCTS_TOSTORE = "PRODUCT.ADD_PRODUCTS_TOSTORE";
export const FETCH_PRODUCTS_FULFILLED = "PRODUCT.FETCH_PRODUCTS_FULFILLED";
export const FETCH_PRODUCTS_REJECTED = "PRODUCT.FETCH_PRODUCTS_REJECTED";

export const ADD_ITEM = "CART.ADD_ITEM";
export const EMPTY_CART = "CART.EMPTY_CART";
export const REMOVE_ITEM = "CART.REMOVE_ITEM";
export const UPDATE_ITEM = "CART.UPDATE_ITEM";

export const ADD_COUPON = "COUPON.ADD_COUPON"

export const ADD_NEW_ORDER = "ORDER.ADD_NEW_ORDER"
export const CANCEL_ORDER = "ORDER.CANCEL_ORDER"
export const FETCH_RECENT_ORDERS = "ORDER.FETCH_RECENT_ORDERS"
export const CANCEL_ORDER_SUCCESS = "ORDER.CANCEL_ORDER_SUCCESS"
export const CANCEL_ORDER_FAILURE = "ORDER.CANCEL_ORDER_FAILURE"
export const FETCH_CANCELLED_ORDERS_FAILURE = "ORDER.FETCH_CANCELLED_ORDERS_FAILURE"
export const FETCH_CANCELLED_ORDERS_SUCCESS = "ORDER.FETCH_CANCELLED_ORDERS_SUCCESS"

export const FETCH_NOTIFICATION = "NOTIFICATION.UPDATE"
export const CANCEL_NOTIFICATION = "NOTIFICATION.DELETE"